[package]
name = "day21"
version = "0.1.0"
authors = ["iDeBugger Freeman <me@idebugger.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
